### ISSUE TITLE
Unable to scan the code with handheld QR Code reader

### ISSUE THREAD

**Issue by SysGreg** [wqweto/VbQRCodegen#3]
[](url)As mentioned, unable to scan the code with handheld E-Pos QR Code reader. iPhone works fine. QR codes generated online works fine with reader, so wonder what doesn't click.

Wonder if the code as option can be generated with text frame like attached example. 

![qr_with_txt](https://user-images.githubusercontent.com/27779211/234364789-78742287-d46b-4b54-b157-6421b053fa37.png)

good job. thanks a lot.
Greg

**Comment by SysGreg** [comment]
Hi. I found the issue. Compared to the original project Nayuki, your codes are flipped (mirrored vertically). Therefore some scanner doesn't read it. See picture below:

![qr_issue](https://user-images.githubusercontent.com/27779211/234371340-f597cfd4-d9ec-465c-a6b5-1d21bb24fa9e.png)

Greg

**Comment by wqweto** [comment]
There was a problem in `QRCodegenResizePicture` procedure which while resizing an StdPicture accidentally flipped the output vertically.

Reopen if https://github.com/wqweto/VbQRCodegen/commit/bcc3fa0ca806b5be39abb828e449c06e9a2a48de  does not fix this issue for you.

**Comment by SysGreg** [comment]
Great, thanks for helping. Codes are now OK.
