### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ajgarrison66** [wqweto/VbQRCodegen#5]
I put the code into my MS Access project.  I put an unbound image on my report.
I used the following to assign a value to the code.  This is on the detail section of the report.
Me![2dbarcode].PictureData = QRCodegenConvertToData(QRCodegenBarcode("'" & Me.CSLabelBC & "'"))

No image shows on my report.  Can you tell me what I have done wrong?

**Comment by wqweto** [comment]
It works here. On a test report I just added `On Format` event procedure for the `Detail` section like this
```
Private Sub Detail_Format(Cancel As Integer, FormatCount As Integer)
    Image7.PictureData = QRCodegenConvertToData(QRCodegenBarcode(Field1.Value))
End Sub
```
. . . and then from View drop down chose Print Preview to get the QR codes generated.

**Comment by ajgarrison66** [comment]
Thank you, I have it working now on a main report.  What if I need it on a subreport.  Moving to a subreport gives a "communication" error to the Image control.

**Comment by wqweto** [comment]
I don't do any MS Access development but it looks like this is not a problem with any of the QRCodegen procedures.

For start try addressing images/fields in subreport without `Me` and without bang operator (`!`) but just plain `QRImage.PictureData` of `QRCodeField.Value`.

**Comment by ajgarrison66** [comment]
I have this working now.  Oddly, I moved the image control to the subreport header, not detail, and it works.  Thank you, this is great code!!!
